name: Close Pull Request
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened]
jobs:
  close_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh pr close ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
