name: Create distribution files for a new release

on:
  release:
    types: [released]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Ubuntu packages
        run: sudo apt install git

      - name: Create Release Branch
        run: |
          branch_name=release-${{ github.ref_name }}
          git checkout -b ${branch_name}
          git remote add local ${{ github.server_url }}/${{ github.repository }}
          git push --set-upstream local ${branch_name}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python packages
        run: >
            pip3 install -U build twine

      - name: Set SOURCE_DATE_EPOCH
        run: >
            echo "SOURCE_DATE_EPOCH=$(git log -n 1 ${{ github.sha }} --format=%ct)" >> $GITHUB_ENV

      - name: Create distribution files
        run: >
            python3 -m build

      - name: Generate Sigstore signatures
        uses: sigstore/gh-action-sigstore-python@1a402ed919f6cb88b9bafb523fb65508c442514b
        with:
          inputs: dist/*

      - name: Check distribution files
        run: >
            twine check dist/*.{tar.gz,whl}

      - name: Calculate checksums for distribution files
        run: >
            sha256sum dist/*.{tar.gz,whl}

      - name: Add files to release
        run: >
            gh release upload ${{ github.ref_name }} dist/*
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Remove Sigstore files
        run: >
            rm -f dist/*.{crt,sig,sigstore}

      - name: Publish distribution files to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
